### ISSUE TITLE
Initialize WordPress from path/port

### ISSUE THREAD

**Issue by jochemstoel** [scottgonzalez/node-wordpress#65]
Hi, I am able to initialize on a custom port number without any problems using the following code:
```js
var wordpress = require("wordpress")
var client = wordpress.createClient({
    url: "myhostname.com:10000",
    username: "admin",
    password: "secret"
})
```
However, when I add an additional path to the url using the code below _(because WordPress is installed in a directory and not on the root)_ it throws an error:

```js
var client = wordpress.createClient({
    url: "myhostname.com:10000/wordpress",
    username: "admin",
    password: "secret"
})
```

```bash
    console.log("Found " + posts.length + " posts!")
                                 ^

TypeError: Cannot read property 'length' of undefined
    at C:\Users\norep\Desktop\wp\test.js:9:34
    at C:\Users\norep\Desktop\wp\node_modules\wordpress\lib\wordpress.js:169:12
    at C:\Users\norep\Desktop\wp\node_modules\wordpress\lib\wordpress.js:102:4
    at C:\Users\norep\Desktop\wp\node_modules\xmlrpc\lib\client.js:130:9
    at Deserializer.callback (C:\Users\norep\Desktop\wp\node_modules\xmlrpc\lib\deserializer.js:30:7)
    at Deserializer.onDone (C:\Users\norep\Desktop\wp\node_modules\xmlrpc\lib\deserializer.js:89:12)
    at SAXStream.emit (events.js:200:13)
    at SAXParser.SAXStream._parser.onend (C:\Users\norep\Desktop\wp\node_modules\sax\lib\sax.js:190:10)
    at emit (C:\Users\norep\Desktop\wp\node_modules\sax\lib\sax.js:624:35)
    at end (C:\Users\norep\Desktop\wp\node_modules\sax\lib\sax.js:667:5)
``` 

I think the reason is because you did not anticipate WordPress being installed into a directory rather than the site's root.

Please instruct on how to proceed from here. Thanks.

**Comment by jochemstoel** [comment]
Be that as it may, try it out yourself. It doesn't work connecting to a url with custom port/path.

**Comment by jochemstoel** [comment]
It is the same WordPress installation running on my localhost. When it is in the public html root folder it works perfectly but when it is installed in a folder it throws an error. As to confirming that the requests are working, well yes I have been doing that so far without problems.

**Comment by jochemstoel** [comment]
To be quite honest I am not too sure how to confirm that XML-RPC is working from a directory. I use your wordpress module as abstraction for all that.
