### ISSUE TITLE
anyone can advice? TypeError: fn is not a function on use client.getPostType

### ISSUE THREAD

**Issue by Prospection** [scottgonzalez/node-wordpress#66]
I am trying to check if post exists, before creating
---------
let wordpress = require("wordpress");
const fs = require('fs');

let client = wordpress.createClient({
    url: "http://example.com/",
    username: "myuser",
    password: "mypass"
});

let is_exists = client.getPostType( 'my title to check');
console.log(is_exists);

--------------
node_modules\wordpress\lib\wordpress.js:207
                        fn( null, fieldMap.from( postType, "postType" ) );
                        ^

TypeError: fn is not a function
    at C:\WEB\...\node_modules\←[4mwordpress←[24m\lib\wordpress.js:207:4
    at C:\WEB\...\node_modules\←[4mwordpress←[24m\lib\wordpress.js:88:12
    at C:\WEB\...\node_modules\←[4mxmlrpc←[24m\lib\client.js:130:9
    at Deserializer.callback (C:\WEB\...\node_modules\←[4mxmlrpc←[24m\lib\deserializer.js:42:7)
    at Deserializer.onDone (C:\WEB\...\node_modules\←[4mxmlrpc←[24m\lib\deserializer.js:92:12)
←[90m    at SAXStream.emit (events.js:210:5)←[39m
    at SAXParser.SAXStream._parser.onend (C:\WEB\....\node_modules\←[4msax←[24m\lib\sax.js:190:10)
    at emit (C:\WEB\....\node_modules\←[4msax←[24m\lib\sax.js:624:35)
    at end (C:\WEB\...\node_modules\←[4msax←[24m\lib\sax.js:667:5)
    at SAXParser.end (C:\WEB\...\node_modules\←[4msax←[24m\lib\sax.js:154:24)

**Comment by scottgonzalez** [comment]
As documented, the method takes a callback; it does not have a return value.
